### PR TITLE
Removing old db relation

### PR DESCRIPTION
**Pull request by gtrkiller**
Remove the old db relation and all the tests associated to it.

### CODE REVIEW

**Review by merkata — DISMISSED** [review]
Looks good! Any changes on documentation necessary? I saw that the tutorial covers the new relation, though still worth checking.

**Review by yanksyoon — DISMISSED** [review]
Looks great! Could you update the docs & remove `ops-lib-mysql` from `requirements.txt` as well please?

**Review by weiiwang01 — DISMISSED** [review]

**Review by yanksyoon — APPROVED** [review]
Thanks for the changes!

**Review by amandahla — APPROVED** [review]
LGTM

**Pull request merged**
