### PR TITLE
update wordpress version in rock to 6.4.1

### PR DESCRIPTION
**Pull request by Thanhphan1147**
Update wordpress's major version from 5.x to 6.x (6.4.1)

- Yoatseo can now be pulled in as latest stable
- default 2023 and 2024 theme breaks integration tests on 6.4.1. Moved 2023 to manual installation and removed 2024 temporary.

Follow up PR would be needed to rework integration tests to be compatible with the 2024 theme

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation is generated using `src-docs`
- [x] The documentation for charmhub is updated.
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by yanksyoon — DISMISSED** [review]
Thanks! LGTM, I believe the plugins are compatible with the major version upgrade?

**Comment by Thanhphan1147** [comment]
yes, I made some changes to themes and plugins with this version upgrade, but nothing too major.

However, it seems that someone mentioned 6.2.3 might not be secure and we should use 6.4+ : https://warthogs.atlassian.net/browse/ISD-1248?focusedCommentId=337218&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-337218

**Comment by Thanhphan1147** [comment]
Blindly updating version to see if integration tests pass.

**Review by amandahla — DISMISSED** [review]
LGTM

**Review by yanksyoon — DISMISSED** [review]
LGTM!

**Review by yanksyoon — APPROVED** [review]

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Pull request merged**
