### PR TITLE
Ignore guzzlehttp CVE in trivy scan

### PR DESCRIPTION
**Pull request by arturo-seijas**
Ignore guzzlehttp CVE in trivy scan

### CODE REVIEW

**Review by yanksyoon — APPROVED** [review]
LGTM!

**Comment by jdkandersson** [comment]
What is the reason please?

**Comment by arturo-seijas** [comment]
> What is the reason please?

Trivy is detecting a new vulnerability in one of the wordpress' dependencies. We can't patch it, we'll need to update wordpress

**Comment by gregory-schiano** [comment]
The build of the image still fails due to the snakeoil key, I think another ignore will have to be added :/

**Comment by amandahla** [comment]
The config file should be considered now, can you try it, please?
See https://github.com/aquasecurity/trivy-action/issues/238

**Comment by arturo-seijas** [comment]
> The config file should be considered now, can you try it, please? See [aquasecurity/trivy-action#238](https://github.com/aquasecurity/trivy-action/issues/238)

It hasn't :( I'll pin to the earlier version for now

**Comment by amandahla** [comment]
My mistake, I saw the merge and then thought that it was related to the action :|

**Review by amandahla — APPROVED** [review]

**Pull request merged**
