### PR TITLE
Remove tls-secret-name configuration

### PR DESCRIPTION
**Pull request by arturo-seijas**
Drop additional_hostnames and tls_secret_name configuration options. This will have to be set directly through the ingress charm

### CODE REVIEW

**Review by gregory-schiano — DISMISSED** [review]
LGTM

**Comment by jdkandersson** [comment]
I think some of the issues causing the workflow failures have been fixed/ are being fixed in this PR: https://github.com/canonical/wordpress-k8s-operator/pull/37

**Comment by merkata** [comment]
Removing code is great, I just don't know why this is being removed :) Can you update the description? Thanks!

**Review by gtrkiller — DISMISSED** [review]
LGTM, but please add a description to the PR

**Review by gtrkiller — APPROVED** [review]
LGTM

**Review by merkata — APPROVED** [review]
Nice, thanks for the description!

**Pull request merged**
