### PR TITLE
Fix variable name

### PR DESCRIPTION
**Pull request by nrobinaubertin**

### CODE REVIEW

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by gregory-schiano — DISMISSED** [review]
LGTM, but you'll unfortunately have to fix the linting and check why one integration test failed :/

**Review by arturo-seijas — CHANGES_REQUESTED** [review]
ops.testing.SIMULATE_CAN_CONNECT is not supported anymore by ops 2. Remove the line instead

**Comment by nrobinaubertin** [comment]
> ops.testing.SIMULATE_CAN_CONNECT is not supported anymore by ops 2. Remove the line instead

I merged origin/main, it's already removed

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Review by gregory-schiano — APPROVED** [review]
LGTM

**Pull request merged**
