### PR TITLE
docs: reference to stable

### PR DESCRIPTION
**Pull request by yanksyoon**
This PR changes the documentation reference from `edge` channel to `stable`.
Furthermore, additional formatting inconsistencies(code formatting, timestamps, reference to wordpress-k8s charm rather than WordPress) are improved and index file(overview documentation) has been added.

### CODE REVIEW

**Review by jdkandersson — DISMISSED** [review]

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by merkata — DISMISSED** [review]
Good changes!
Irrelevant of that I notice some tests are failing, anyone know why that is?

**Comment by nrobinaubertin** [comment]
> Good changes! Irrelevant of that I notice some tests are failing, anyone know why that is?

[Here](https://github.com/canonical/wordpress-k8s-operator/actions/runs/4342583201/jobs/7625667707#step:15:248) it looks like loki-k8s got stuck installing its agent.  
This happens to me locally sometimes too. It may be a network issue (some congestion ?).  
I hope to control it more locally by having a local registry for charms and images.

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by weiiwang01 — APPROVED** [review]

**Review by jdkandersson — APPROVED** [review]

**Pull request merged**
